import Image from "next/image";
import { Mail, Phone } from "lucide-react";
import { MotionReveal } from "@/components/motion-reveal";
import { contactDetails } from "@/lib/content";

export function FounderSection() {
  return <section className="w-full bg-[#fdfcf9]"><div className="page-shell section-space"><div className="grid grid-cols-1 gap-16 lg:grid-cols-[minmax(0,360px)_1fr] lg:gap-24 xl:gap-32">
    <MotionReveal className="lg:pt-56"><div className="flex items-end gap-5"><div><p className="display text-xl">Rockville Legal Practitioners</p><p className="mt-1 text-sm text-stone">The founding partners</p></div><svg aria-hidden="true" width="110" height="44" viewBox="0 0 110 44" className="mb-1 text-line"><path d="M4 30 C 18 8, 26 8, 30 22 C 33 32, 40 32, 46 18 C 50 8, 56 8, 58 20 C 60 30, 66 14, 74 12 C 82 10, 88 24, 100 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></svg></div><div className="relative mt-9 aspect-[3/4] w-full overflow-hidden"><Image src="/images/founders-placeholder.jpg" alt="Founding partners portrait placeholder" fill sizes="(min-width: 1024px) 360px, 100vw" className="object-cover grayscale" /></div></MotionReveal>
    <div className="flex flex-col"><MotionReveal><p className="eyebrow brand-rule text-stone">Our founders’ story</p><h2 className="display mt-7 text-[clamp(2.8rem,5vw,5.4rem)] leading-[.98]">Values that matter deeply to us: integrity, commitment, and counsel that earns confidence.</h2></MotionReveal><MotionReveal><div className="mt-12 border-t border-line pt-10 sm:grid sm:grid-cols-[1fr_auto] sm:gap-10"><div className="max-w-[49ch] space-y-6 text-base leading-7 text-stone md:text-lg md:leading-8"><p>We founded this firm because we believed clients deserved a different kind of legal experience—one grounded not only in skill and strategy, but also in empathy, trust, and true personal commitment. Legal matters should never leave people uncertain or unheard.</p><p>For us, practising law has always been about more than solving problems. It is about helping people and businesses move forward with clarity, confidence, and trusted support.</p></div><span aria-hidden="true" className="display text-8xl leading-none text-line md:text-9xl">”</span></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-4"><a href={`mailto:${contactDetails.email}`} className="flex items-center gap-3 text-sm"><span className="flex h-12 w-12 items-center justify-center bg-panel"><Mail size={19} strokeWidth={1.4} /></span>{contactDetails.email}</a><a href="tel:+2348033064300" className="flex items-center gap-3 text-sm"><span className="flex h-12 w-12 items-center justify-center bg-panel"><Phone size={19} strokeWidth={1.4} /></span>{contactDetails.phonePrimary}</a></div></MotionReveal></div>
  </div></div></section>;
}
