import { Mail, Phone } from "lucide-react";
import { MotionReveal } from "@/components/motion-reveal";
import { TeamPortraitFrame } from "@/components/team-portrait-frame";
import { contactDetails, teamMembers } from "@/lib/content";

export function TeamProfiles() {
  return <>{teamMembers.map((member) => <section data-team-profile data-team-story-layout="founder-story" key={member.name} className="w-full bg-[#fdfcf9]"><div className="page-shell section-space"><div className="grid grid-cols-1 gap-16 lg:grid-cols-[minmax(0,360px)_1fr] lg:gap-24 xl:gap-32">
    <MotionReveal className="lg:pt-56"><div className="flex items-end gap-5"><div><p className="display text-xl">{member.name}</p><p className="mt-1 text-sm text-stone">{member.role}</p></div><svg aria-hidden="true" width="110" height="44" viewBox="0 0 110 44" className="mb-1 text-line"><path d="M4 30 C 18 8, 26 8, 30 22 C 33 32, 40 32, 46 18 C 50 8, 56 8, 58 20 C 60 30, 66 14, 74 12 C 82 10, 88 24, 100 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></svg></div><div className="mt-9"><TeamPortraitFrame member={member} variant="profile" /></div></MotionReveal>
    <div className="flex flex-col"><MotionReveal><p className="eyebrow brand-rule text-stone">Our team member’s story</p><h2 className="display mt-7 text-[clamp(2.8rem,5vw,5.4rem)] leading-[.98]">{member.storyTitle}</h2></MotionReveal><MotionReveal><div className="mt-12 border-t border-line pt-10 sm:grid sm:grid-cols-[1fr_auto] sm:gap-10"><div className="max-w-[49ch] space-y-6 text-base leading-7 text-stone md:text-lg md:leading-8">{member.profile.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><span aria-hidden="true" className="display text-8xl leading-none text-line md:text-9xl">”</span></div><div role="group" aria-label="Team profile contact details" className="mt-12 flex flex-wrap gap-x-8 gap-y-4"><a href={`mailto:${contactDetails.email}`} className="flex items-center gap-3 text-sm"><span className="flex h-12 w-12 items-center justify-center bg-panel"><Mail aria-hidden="true" size={19} strokeWidth={1.4} /></span>{contactDetails.email}</a><a href="tel:+2348033064300" className="flex items-center gap-3 text-sm"><span className="flex h-12 w-12 items-center justify-center bg-panel"><Phone aria-hidden="true" size={19} strokeWidth={1.4} /></span>{contactDetails.phonePrimary}</a></div></MotionReveal></div>
  </div></div></section>)}</>;
}
